# @package _global_

defaults:
  - _self_
  - env: null
  - model: null
  - policy_net: null

  - experiment: null

  - override hydra/job_logging: custom

hydra:
  output_subdir: null
  run:
    dir: .


# number of envs to train model
n_envs: 4

# The total number of samples (env steps) to train on
total_timesteps: 20_000

# The number of episodes before logging.
log_interval: 1_000

# eval_frequency to save model and make gif, eval_frequency have to be >= 1
eval_frequency: 2

# dir of storage all experiments
path_to_outputs: "outputs/experiments"

# description of experiment
description: "This is experiment description, we can write whatever we want"
experiment_name: "name"

# XXXXXXXXXXXX number of games to generate gif
eval_games_number: 1
